import { Conteudo } from './types';

// URLs base para construção dos links de imagens e vídeos.
export const baseUrlPoster = "https://image.tmdb.org/t/p/w500";
export const baseUrlImagemFundo = "https://image.tmdb.org/t/p/original";
export const baseUrlVideo = "https://storage.googleapis.com/gtv-videos-bucket/sample/";

export const filmesPopulares: Conteudo[] = [
  {
    id: 1,
    tipo: 'movie',
    titulo: "Duna: Parte Dois",
    avaliacao: 8.2,
    poster: baseUrlPoster + "/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    ano: 2024,
    duracao: "2h 46min",
    generos: ["Ficção Científica", "Aventura"],
    descricao: "Paul Atreides se une a Chani e aos Fremen em uma guerra de vingança contra os conspiradores que destruíram sua família.",
    imagemFundo: baseUrlImagemFundo + "/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    urlTrailer: "https://www.youtube.com/embed/U2Qp5pL3ovA",
    urlVideo: baseUrlVideo + "TearsOfSteel.mp4",
  },
  {
    id: 2,
    tipo: 'movie',
    titulo: "Oppenheimer",
    avaliacao: 8.6,
    poster: baseUrlPoster + "/1OsQJEoSXBjduuCvDOlRhoEUaHu.jpg",
    ano: 2023,
    duracao: "3h 0min",
    generos: ["Drama", "História"],
    descricao: "A história do físico americano J. Robert Oppenheimer e seu papel no desenvolvimento da bomba atômica.",
    imagemFundo: baseUrlImagemFundo + "/H6vke7zGiuLsz4v4RPeReb9rI25.jpg",
    urlTrailer: "https://www.youtube.com/embed/F1eO-Oq2FII",
    urlVideo: baseUrlVideo + "BigBuckBunny.mp4",
  },
  {
    id: 3,
    tipo: 'movie',
    titulo: "Mad Max: Estrada da Fúria",
    avaliacao: 8.1,
    poster: baseUrlPoster + "/mtgqrSlT47VsmeMVanLTny7BknB.jpg",
    ano: 2015,
    duracao: "2h 0min",
    generos: ["Ação", "Aventura", "Ficção Científica"],
    descricao: "Em um mundo pós-apocalíptico, Max se une a Furiosa, uma mulher que tenta salvar um grupo de garotas de um líder tirano.",
    imagemFundo: baseUrlImagemFundo + "/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg",
    urlTrailer: "https://www.youtube.com/embed/hEJnMQG9ev8",
    urlVideo: baseUrlVideo + "ForBiggerFun.mp4",
  },
  {
    id: 4,
    tipo: 'movie',
    titulo: "Pobres Criaturas",
    avaliacao: 8.0,
    poster: baseUrlPoster + "/iOdcXYSVzBgmBJzNIlIMOZ6fz0F.jpg",
    ano: 2023,
    duracao: "2h 21min",
    generos: ["Ficção Científica", "Drama", "Comédia"],
    descricao: "A fantástica evolução de Bella Baxter, uma jovem trazida de volta à vida pelo brilhante e heterodoxo cientista Dr. Godwin Baxter.",
    imagemFundo: baseUrlImagemFundo + "/sNbDbkYh6mN0SPa9sUXmOa9Mour.jpg",
    urlTrailer: "https://www.youtube.com/embed/RlbR5N6veqw",
    urlVideo: baseUrlVideo + "ElephantsDream.mp4",
  },
  {
    id: 5,
    tipo: 'movie',
    titulo: "O Senhor dos Anéis: O Retorno do Rei",
    avaliacao: 9.0,
    poster: baseUrlPoster + "/egSO4klmc9pnI1CNnHoYKV70XKI.jpg",
    ano: 2003,
    duracao: "3h 21min",
    generos: ["Aventura", "Fantasia", "Ação"],
    descricao: "Gandalf e Aragorn lideram o Mundo dos Homens contra o exército de Sauron para desviar o olhar de Frodo e Sam, que se aproximam do Monte da Perdição com o Um Anel.",
    imagemFundo: baseUrlImagemFundo + "/rCgsG4b84I2j1a3H3wKl1a4Yl94.jpg",
    urlTrailer: "https://www.youtube.com/embed/r5X-hFf6Bwo",
    urlVideo: baseUrlVideo + "Sintel.mp4",
  },
  {
    id: 6,
    tipo: 'movie',
    titulo: "Parasita",
    avaliacao: 8.5,
    poster: baseUrlPoster + "/bik2BZjmVjeE6LOZqtuTjb4jJPQ.jpg",
    ano: 2019,
    duracao: "2h 12min",
    generos: ["Comédia", "Thriller", "Drama"],
    descricao: "Uma família pobre se infiltra na casa de uma família rica, desencadeando uma série de eventos inesperados.",
    imagemFundo: baseUrlImagemFundo + "/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg",
    urlTrailer: "https://www.youtube.com/embed/9w_V03p0egw",
    urlVideo: baseUrlVideo + "SubaruOutbackOnStreetAndDirt.mp4",
  },
];

export const lancamentos: Conteudo[] = [
  {
    id: 7,
    tipo: 'movie',
    titulo: "Guerra Civil",
    avaliacao: 7.9,
    poster: baseUrlPoster + "/3Use5sOQWXL3BvcaKqUH7eQ7I53.jpg",
    ano: 2024,
    duracao: "1h 49min",
    generos: ["Ação", "Guerra", "Drama"],
    descricao: "Uma equipe de jornalistas viaja pelos Estados Unidos durante uma guerra civil que se intensifica rapidamente.",
    imagemFundo: baseUrlImagemFundo + "/z12hDweP4d1Rj7sL3alN9DebV4E.jpg",
    urlTrailer: "https://www.youtube.com/embed/6o8m0sDd4e4",
    urlVideo: baseUrlVideo + "ForBiggerBlazes.mp4",
  },
  {
    id: 8,
    tipo: 'movie',
    titulo: "Godzilla x Kong: O Novo Império",
    avaliacao: 7.2,
    poster: baseUrlPoster + "/teW53VSLdZMMSmkn5xBBowu3tEr.jpg",
    ano: 2024,
    duracao: "1h 55min",
    generos: ["Ação", "Ficção Científica", "Aventura"],
    descricao: "Dois antigos titãs, Godzilla e Kong, se enfrentam em uma batalha épica enquanto os humanos desvendam suas origens entrelaçadas.",
    imagemFundo: baseUrlImagemFundo + "/2C3mMUrFz6aX2NB3kM6Exxxit2k.jpg",
    urlTrailer: "https://www.youtube.com/embed/qqrpMRDuPfc",
    urlVideo: baseUrlVideo + "ForBiggerEscapes.mp4",
  },
  {
    id: 9,
    tipo: 'movie',
    titulo: "A Primeira Profecia",
    avaliacao: 6.9,
    poster: baseUrlPoster + "/ySgY4jBvZ6qchrxKnBg4M8tZp8V.jpg",
    ano: 2024,
    duracao: "2h 0min",
    generos: ["Terror"],
    descricao: "Uma jovem americana é enviada a Roma para começar uma vida de serviço à igreja e descobre uma conspiração aterrorizante.",
    imagemFundo: baseUrlImagemFundo + "/cIztATgG2iW1Lp3uA8aFz3h2sP.jpg",
    urlTrailer: "https://www.youtube.com/embed/5g3zFvX_TBU",
    urlVideo: baseUrlVideo + "WeAreGoingOnBullrun.mp4",
  },
  {
    id: 10,
    tipo: 'movie',
    titulo: "Kung Fu Panda 4",
    avaliacao: 7.1,
    poster: baseUrlPoster + "/vU5MZaZfdl6P7SRHGjpWYiNYa1t.jpg",
    ano: 2024,
    duracao: "1h 34min",
    generos: ["Animação", "Ação", "Comédia"],
    descricao: "Po deve treinar um novo Guerreiro Dragão para enfrentar uma feiticeira malvada que pode se transformar em qualquer criatura.",
    imagemFundo: baseUrlImagemFundo + "/kYgQzzjNis5jJalYtIpb2gKsv2d.jpg",
    urlTrailer: "https://www.youtube.com/embed/_inKs4eeHiI",
    urlVideo: baseUrlVideo + "ForBiggerJoyrides.mp4",
  },
  {
    id: 11,
    tipo: 'movie',
    titulo: "Ghostbusters: Apocalipse de Gelo",
    avaliacao: 6.7,
    poster: baseUrlPoster + "/pPJX925yPfqUPsNnOx9We6tppD4.jpg",
    ano: 2024,
    duracao: "1h 55min",
    generos: ["Comédia", "Aventura", "Fantasia"],
    descricao: "A família Spengler retorna para onde tudo começou - o icônico quartel de bombeiros de Nova York.",
    imagemFundo: baseUrlImagemFundo + "/s9hW1DHf1RjD8D8Y542a2mD7S4Y.jpg",
    urlTrailer: "https://www.youtube.com/embed/1i2u-o_pY_M",
    urlVideo: baseUrlVideo + "TearsOfSteel.mp4",
  },
  {
    id: 12,
    tipo: 'movie',
    titulo: "Fúria Primitiva",
    avaliacao: 7.3,
    poster: baseUrlPoster + "/y6bZk79VHK4XvZo6dAJd6Z9JgKq.jpg",
    ano: 2024,
    duracao: "2h 1min",
    generos: ["Ação", "Thriller"],
    descricao: "Um jovem anônimo desencadeia uma campanha de vingança contra os líderes corruptos que assassinaram sua mãe.",
    imagemFundo: baseUrlImagemFundo + "/1G4U2FmhA025055bLhS4g2S2c3.jpg",
    urlTrailer: "https://www.youtube.com/embed/ooI5hH-ePno",
    urlVideo: baseUrlVideo + "WhatCarCanYouGetForAGrand.mp4",
  },
];

export const classicosCinema: Conteudo[] = [
  {
    id: 13,
    tipo: 'movie',
    titulo: "O Poderoso Chefão",
    avaliacao: 9.2,
    poster: baseUrlPoster + "/uP46DujkD3nwcisOjz9a0Xw0Knj.jpg",
    ano: 1972,
    duracao: "2h 55min",
    generos: ["Drama", "Crime"],
    descricao: "O patriarca de uma dinastia do crime organizado transfere o controle de seu império clandestino para seu filho relutante.",
    imagemFundo: baseUrlImagemFundo + "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    urlTrailer: "https://www.youtube.com/embed/sa5S_8DAw-I",
    urlVideo: baseUrlVideo + "BigBuckBunny.mp4",
  },
  {
    id: 14,
    tipo: 'movie',
    titulo: "A Lista de Schindler",
    avaliacao: 8.9,
    poster: baseUrlPoster + "/fvPYwfXH513e8Nqe0kzWFm2jjg.jpg",
    ano: 1993,
    duracao: "3h 15min",
    generos: ["Drama", "História", "Guerra"],
    descricao: "Na Polônia ocupada pelos alemães durante a Segunda Guerra Mundial, o industrial Oskar Schindler gradualmente se preocupa com sua força de trabalho judaica.",
    imagemFundo: baseUrlImagemFundo + "/zb6fM1CX41D9rF9hdgppUeviklv.jpg",
    urlTrailer: "https://www.youtube.com/embed/gG22XNhtnoY",
    urlVideo: baseUrlVideo + "Sintel.mp4",
  },
  {
    id: 15,
    tipo: 'movie',
    titulo: "Pulp Fiction: Tempo de Violência",
    avaliacao: 8.9,
    poster: baseUrlPoster + "/tptjnB2LDbuUWya9Cx5sQtv5hqb.jpg",
    ano: 1994,
    duracao: "2h 34min",
    generos: ["Thriller", "Crime"],
    descricao: "As vidas de dois assassinos de aluguel, um boxeador, a esposa de um gângster e um par de bandidos de lanchonete se entrelaçam em quatro contos de violência e redenção.",
    imagemFundo: baseUrlImagemFundo + "/ejdD20cdHNFAYAN2Htn2uP6m2j9.jpg",
    urlTrailer: "https://www.youtube.com/embed/s7EdQ4FqbhY",
    urlVideo: baseUrlVideo + "ForBiggerFun.mp4",
  },
  {
    id: 16,
    tipo: 'movie',
    titulo: "Forrest Gump: O Contador de Histórias",
    avaliacao: 8.8,
    poster: baseUrlPoster + "/d74WpIsH8379TIL4wUxDneRCYv2.jpg",
    ano: 1994,
    duracao: "2h 22min",
    generos: ["Comédia", "Drama", "Romance"],
    descricao: "As presidências de Kennedy e Johnson, a Guerra do Vietnã, o escândalo de Watergate e outros eventos históricos se desenrolam através da perspectiva de um homem do Alabama.",
    imagemFundo: baseUrlImagemFundo + "/3h1JZGDhZ8nzxdgvkxhaSErXDbv.jpg",
    urlTrailer: "https://www.youtube.com/embed/bLvqoHBptjg",
    urlVideo: baseUrlVideo + "ElephantsDream.mp4",
  },
  {
    id: 17,
    tipo: 'movie',
    titulo: "Clube da Luta",
    avaliacao: 8.8,
    poster: baseUrlPoster + "/nu7FEmC4zBaZ7c3QYmVpDlZa2H0.jpg",
    ano: 1999,
    duracao: "2h 19min",
    generos: ["Drama"],
    descricao: "Um trabalhador de escritório com insônia, procurando uma maneira de mudar sua vida, cruza o caminho com um fabricante de sabão e eles formam um clube de luta clandestino.",
    imagemFundo: baseUrlImagemFundo + "/hZkgoQYus5vegHoetLkJoBpiGOP.jpg",
    urlTrailer: "https://www.youtube.com/embed/SUXWAEX2jlg",
    urlVideo: baseUrlVideo + "TearsOfSteel.mp4",
  },
  {
    id: 18,
    tipo: 'movie',
    titulo: "Matrix",
    avaliacao: 8.7,
    poster: baseUrlPoster + "/lDqMDI3xpbB9UQRyeXfei0MXhqb.jpg",
    ano: 1999,
    duracao: "2h 16min",
    generos: ["Ação", "Ficção Científica"],
    descricao: "Um hacker de computador aprende com misteriosos rebeldes sobre a verdadeira natureza de sua realidade e seu papel na guerra contra seus controladores.",
    imagemFundo: baseUrlImagemFundo + "/gfJGlDaHuWimErCr5Ql0I8x9QSy.jpg",
    urlTrailer: "https://www.youtube.com/embed/m8e-FF8MsqU",
    urlVideo: baseUrlVideo + "ForBiggerEscapes.mp4",
  },
];
